# Joins

Los *joins* sirven para combinar tablas relacionadas usando una o varias columnas en común.

In [ ]:
import pandas as pd

In [ ]:
especies = pd.DataFrame({
    "id_especie": [1, 2, 3, 4],
    "especie": ["Homo sapiens", "Pan troglodytes",
                "Mus musculus", "Danio rerio"]
})

In [ ]:
especies

   id_especie          especie
0           1     Homo sapiens
1           2  Pan troglodytes
2           3     Mus musculus
3           4      Danio rerio

In [ ]:
muestras = pd.DataFrame({
    "id_muestra": [101, 102, 103, 104, 105],
    "id_especie": [1, 2, 1, 3, 99],
    "tejido": ["sangre", "músculo", "hígado", "cerebro", "piel"]
})

In [ ]:
muestras

   id_muestra  id_especie   tejido
0         101           1   sangre
1         102           2  músculo
2         103           1   hígado
3         104           3  cerebro
4         105          99     piel

¿Qué columna podemos usar para relacionar ambas tablas?

## Inner Join

In [ ]:
resultado = pd.merge(
    muestras,
    especies,
    on="id_especie",
     )

In [ ]:
resultado

### Ejercicio:

Importar y hacer un `inner join` con las siguientes tablas:

https://raw.githubusercontent.com/Nesper94/ciencia-de-datos/refs/heads/main/datos/especies.csv  
https://raw.githubusercontent.com/Nesper94/ciencia-de-datos/refs/heads/main/datos/observaciones.csv

- ¿Hay especies sin observaciones?
- ¿Hay observaciones sin datos sobre la especie?
- ¿En qué departamentos se ha observado cada especie?

## Left Join

El *left join* conserva todas las filas de la tabla de la izquierda, aunque no tengan correspondencia a la derecha.

In [ ]:
muestras

In [ ]:
especies

Si elegimos la tabla `especies` como tabla de la izquierda:

In [ ]:
resultado = pd.merge(
    especies,
    muestras,
    on="id_especie",
    how="left"
)

In [ ]:
resultado

Si elegimos la tabla `muestras` como tabla de la izquierda:

In [ ]:
resultado = pd.merge(
    muestras,
    especies,
    on='id_especie',
    how='left'
)

In [ ]:
resultado

### Ejercicio

Hacer un *left join* con las tablas `especies.csv` (izquierda), y `observaciones.csv` (derecha).

## Right Join

Es lo contrario del *left join*: conserva todas las filas de la tabla de la derecha.

In [ ]:
resultado = pd.merge(
    muestras,
    especies,
    on="id_especie",
    how="right"
)

In [ ]:
resultado

### Ejercicio

Hacer un *right join* con las tablas `especies.csv` (izquierda), y `observaciones.csv` (derecha).

## Full Outer Join

También llamado *full join* u *outer join*.  
Conserva todas las filas de ambas tablas, tengan o no correspondencia.

In [ ]:
muestras

   id_muestra  id_especie   tejido
0         101           1   sangre
1         102           2  músculo
2         103           1   hígado
3         104           3  cerebro
4         105          99     piel

In [ ]:
especies

   id_especie          especie
0           1     Homo sapiens
1           2  Pan troglodytes
2           3     Mus musculus
3           4      Danio rerio

In [ ]:
resultado = pd.merge(
    muestras,
    especies,
    on="id_especie",
    how="outer"
)

In [ ]:
resultado

   id_muestra  id_especie   tejido          especie
0       101.0           1   sangre     Homo sapiens
1       103.0           1   hígado     Homo sapiens
2       102.0           2  músculo  Pan troglodytes
3       104.0           3  cerebro     Mus musculus
4         NaN           4      NaN      Danio rerio
5       105.0          99     piel              NaN

### Ejercicio

Con las tablas `especies.csv` y `observaciones.csv`, haga un *full outer join* y luego calcule el número total de individuos observados por grupo: mamíferos, aves, reptiles, anfibios y plantas.

Recordar la operación `groupby`:

`df.groupby('columna_grupos')['columna_de_interés'].sum()`

## Join usando nombres de columnas diferentes

No siempre las columnas tienen el mismo nombre.  
Por ejemplo:

In [ ]:
especies = pd.DataFrame({
    "codigo": [1, 2, 3],
    "especie": ["Homo sapiens", "Mus musculus", "Danio rerio"]
})

muestras = pd.DataFrame({
    "id_muestra": [101, 102, 103],
    "id_especie": [1, 2, 3]
})

In [ ]:
especies

   codigo       especie
0       1  Homo sapiens
1       2  Mus musculus
2       3   Danio rerio

In [ ]:
muestras

   id_muestra  id_especie
0         101           1
1         102           2
2         103           3

In [ ]:
resultado = pd.merge(
    muestras,
    especies,
    left_on="id_especie",
    right_on="codigo",
    how="inner"
)

In [ ]:
resultado

   id_muestra  id_especie  codigo       especie
0         101           1       1  Homo sapiens
1         102           2       2  Mus musculus
2         103           3       3   Danio rerio

### Ejercicio

Crear dos tablas de pandas sencillas, que compartan una columna pero cuyo nombre sea diferente en las dos tablas. Luego hacer un *inner join*.

## Join usando varias columnas

In [ ]:
expresión = pd.DataFrame({
    "especie": ["humano", "humano", "ratón", "ratón"],
    "gen": ["TP53", "BRCA1", "Tp53", "Brca1"],
    "expresion": [12.4, 8.7, 15.2, 6.1]
})

In [ ]:
expresión

  especie    gen  expresion
0  humano   TP53       12.4
1  humano  BRCA1        8.7
2   ratón   Tp53       15.2
3   ratón  Brca1        6.1

In [ ]:
genes = pd.DataFrame({
    "especie": ["humano", "humano", "ratón", "ratón"],
    "gen": ["TP53", "BRCA1", "Tp53", "Brca1"],
    "funcion": [
        "supresor tumoral",
        "reparación del ADN",
        "supresor tumoral",
        "reparación del ADN"
    ]
})

In [ ]:
genes

  especie    gen             funcion
0  humano   TP53    supresor tumoral
1  humano  BRCA1  reparación del ADN
2   ratón   Tp53    supresor tumoral
3   ratón  Brca1  reparación del ADN

In [ ]:
resultado = pd.merge(
    expresión,
    genes,
    on=["especie", "gen"],
    how="inner"
)

In [ ]:
resultado

  especie    gen  expresion             funcion
0  humano   TP53       12.4    supresor tumoral
1  humano  BRCA1        8.7  reparación del ADN
2   ratón   Tp53       15.2    supresor tumoral
3   ratón  Brca1        6.1  reparación del ADN

## Resumen

Recordando la siguiente estructura podemos hacer la mayoría de los joins:

```python
pd.merge(
    tabla_izquierda,
    tabla_derecha,
    on="columna_clave",
    how="left" # Tipo de join
)
```